[project]
name = "research-assistant"
version = "0.1.0"
description = "AI powered research assistant"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crewai>=1.6.1",
    "dotenv>=0.9.9",
    "langchain>=1.1.3",
    "langchain-openai>=1.1.1",
    "openai>=2.9.0",
    "reportlab>=4.4.6",
    "requests>=2.32.5",
    "streamlit>=1.52.1",
]

[dependency-groups]
lint = [
    "pyrefly>=0.45.2",
    "ruff>=0.14.8",
]
