name: Lint

on:
  - push
  - pull_request

permissions:
  contents: read
  pull-requests: read

jobs:
  type-check:
    strategy:
      matrix:
        python-version: [ '3.12' ]
    name: Type Checking
    uses: SanctumLabs/ci-workflows/.github/workflows/python-lint.yml@main
    with:
      command: make pyrefly
      python-version: ${{ matrix.python-version }}
      packager: uv

  lint:
    strategy:
      matrix:
        python-version: [ '3.12' ]
    name: Ruff
    uses: SanctumLabs/ci-workflows/.github/workflows/python-lint.yml@main
    with:
      command: make ruff
      python-version: ${{ matrix.python-version }}
      packager: uv